# Generated by Django 3.1.1 on 2020-09-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopingpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
    ]
