# Generated by Django 3.1.1 on 2020-09-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingpages', '0002_auto_20200902_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, help_text='Сума у гривнях', verbose_name='Ціна товару'),
        ),
    ]
