# Generated by Django 3.1.1 on 2020-09-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopingpages', '0003_auto_20200902_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'Додати товар у магазин', 'verbose_name_plural': 'Додати товар у магазин'},
        ),
    ]
