# Generated by Django 3.1.1 on 2020-09-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopingpages', '0004_auto_20200902_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Good',
            new_name='Goods',
        ),
    ]
